BlogFilipe.web/Models/Blog/DetalhesPostViewModel.cs
using BlogFilipe.DB.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlogFilipe.web.Models.Blog
{
    public class DetalhesPostViewModel
    {
        public int Id { get; set; }
        public int QtdeComentarios { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string Resumo { get; set; }
        public string Descricao { get; set; }
        public DateTime DataPublicacao { get; set; }
        public DateTime HoraPublicacao { get; set; }
        public bool Visivel { get; set; }

        public List<string> Tags { get; set; }

        [DisplayName("Nome")]
        [StringLength(100, ErrorMessage ="O campo nome deve possuir no máximo {1} caracteres!")]
        [Required(ErrorMessage ="O campo nome é obrigtório!")]
        public string ComentarioNome { get; set; }

        [DisplayName("E-mail")]
        [StringLength(100, ErrorMessage ="O campo E-mail deve possuir no máximo {1} caracteres!")]
        [EmailAddress(ErrorMessage ="E-mail inválido")]
        public string ComentarioEmail { get; set; }

        [DisplayName("Descricao")]
        [Required(ErrorMessage ="O campo descrição é obrigatório!")]
        public string ComentarioDescricao { get; set; }

        [DisplayName("Página Web")]
        [StringLength(100, ErrorMessage ="O campo página web deve possuir no máximo {1} caracteres!")]
        public string ComentarioPaginaWeb { get; set; }

        public int PaginaAtual { get; set; }
        public int TotalPaginas { get; set; }
        public IList<Comentario> Comentarios { get; set; }
    }
}

BlogFilipe.web/Models/Blog/ListarPostsViewModel.cs
using BlogFilipe.DB.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogFilipe.web.Models.Blog
{
    public class ListarPostsViewModel
    {
        public List<DetalhesPostViewModel> Posts { get; set; }
        public int PaginaAtual { get; set; }
        public int TotalPaginas { get; set; }
        public string Tag { get; set; }
        public string Pesquisa { get; set; }
        public List<string> Tags { get; set; }
    }
}

BlogFilipe.web/Controllers/AdministracaoController.cs
using BlogFilipe.DB;
using BlogFilipe.DB.Classes;
using BlogFilipe.web.Models.Administracao;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFilipe.web.Controllers
{
    [Authorize]
    public class AdministracaoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        #region CadastrarPost
        [HttpGet]
        public ActionResult CadastrarPost()
        {
            var viewModel = new CadastrarPostViewModel();

            viewModel.Autor = "Filipe";
            viewModel.DataPublicacao = DateTime.Now;
            viewModel.HoraPublicacao = DateTime.Now;
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CadastrarPost(CadastrarPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new ConexaoBanco();
                var post = new Post();

                post.Titulo = viewModel.Titulo;
                post.Autor = viewModel.Autor;
                post.Resumo = viewModel.Resumo;
                post.Descricao = viewModel.Descricao;
                post.Visivel = viewModel.Visivel;
                post.DataPublicacao = viewModel.DataPublicacao.Add(viewModel.HoraPublicacao.TimeOfDay);
                post.TagsPost = new List<TagPost>();

                if (viewModel.Tags != null)
                {
                    foreach (var item in viewModel.Tags)
                    {
                        var tagExiste = (from p in conexao.TagClass
                                         where p.Tag.ToLower() == item.ToLower()
                                         select p).Any();

                        if (!tagExiste)
                        {
                            var tagClass = new TagClass();
                            tagClass.Tag = item;
                            conexao.TagClass.Add(tagClass);
                        }

                        var tagPost = new TagPost();
                        tagPost.IdTag = item;
                        post.TagsPost.Add(tagPost);
                    }
                }

                conexao.Posts.Add(post);

                try
                {
                    conexao.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View(viewModel);
        }
        #endregion

        #region EditarPost
        public ActionResult EditarPost(int id)
        {
            var viewModel = new CadastrarPostViewModel();
            var conexao = new ConexaoBanco();

            var post = (from x in conexao.Posts where x.Id == id select x).FirstOrDefault();

            if (post == null)
            {
                throw new Exception(string.Format("Erro"));
            }
            else
            {
                viewModel.Autor = post.Autor;
                viewModel.DataPublicacao = post.DataPublicacao;
                viewModel.Descricao = post.Descricao;
                viewModel.HoraPublicacao = post.DataPublicacao;
                viewModel.Resumo = post.Resumo;
                viewModel.Titulo = post.Titulo;
                viewModel.Visivel = post.Visivel;
                viewModel.Tags = (from p in post.TagsPost
                                  select p.IdTag).ToList();
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditarPost(CadastrarPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new ConexaoBanco();
                var post = conexao.Posts.FirstOrDefault(x => x.Id == viewModel.Id);

                post.Titulo = viewModel.Titulo;
                post.Autor = viewModel.Autor;
                post.Resumo = viewModel.Resumo;
                post.Descricao = viewModel.Descricao;
                post.Visivel = viewModel.Visivel;
                post.DataPublicacao = viewModel.DataPublicacao.Add(viewModel.HoraPublicacao.TimeOfDay);

                var tagPostAtual = post.TagsPost.ToList();

                foreach (var item in tagPostAtual)
                {
                    conexao.TagPosts.Remove(item);
                }

                if (viewModel.Tags != null)
                {
                    foreach (var item in viewModel.Tags)
                    {
                        var tagExiste = (from p in conexao.TagClass
                                         where p.Tag.ToLower() == item.ToLower()
                                         select p).Any();

                        if (!tagExiste)
                        {
                            var tagClass = new TagClass();
                            tagClass.Tag = item;
                            conexao.TagClass.Add(tagClass);
                        }

                        var tagPost = new TagPost();
                        tagPost.IdTag = item;
                        post.TagsPost.Add(tagPost);
                    }
                }

                try
                {
                    conexao.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            return View(viewModel);
        }
        #endregion

        public ActionResult ExcluirPost(int id)
        {
            var conexao = new ConexaoBanco();

            var post = conexao.Posts.FirstOrDefault(x => x.Id == id);

            if( post == null)
            {
                throw new Exception(string.Format("Erro"));
            }

            conexao.Posts.Remove(post);
            conexao.SaveChanges();

            return RedirectToAction("Index", "Blog");
        }

        #region ExcluirComentario
        public ActionResult ExcluirComentario(int id)
        {
            var conexaoBanco = new ConexaoBanco();
            var comentario = (from p in conexaoBanco.Comentarios
                              where p.Id == id
                              select p).FirstOrDefault();
            if (comentario == null)
            {
                throw new Exception(string.Format("Comentário código {0} não foi encontrado.", id));
            }
            conexaoBanco.Comentarios.Remove(comentario);
            conexaoBanco.SaveChanges();

            var post = (from p in conexaoBanco.Posts
                        where p.Id == comentario.IdPost
                        select p).First();
            return Redirect(Url.Action("Post", "Blog", new
            {
                ano = post.DataPublicacao.Year,
                mes = post.DataPublicacao.Month,
                dia = post.DataPublicacao.Day,
                titulo = post.Titulo,
                id = post.Id
            }) + "#comentarios");
        }
        #endregion
    }
}

BlogFilipe.web/Controllers/BlogController.cs
using BlogFilipe.DB;
using BlogFilipe.DB.Classes;
using BlogFilipe.web.Models.Administracao;
using BlogFilipe.web.Models.Blog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFilipe.web.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index(int? pagina, string tag, string pesquisa)
        {
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registrosPorPagina = 10;

            var conexao = new ConexaoBanco();
            var viewModel = new ListarPostsViewModel();

            List<Post> posts = (from p in conexao.Posts
                                where p.Visivel == true
                                select p).ToList();

            if (!string.IsNullOrEmpty(tag))
            {
                posts = (from p in posts
                         where p.TagsPost.Any(x => x.IdTag.ToUpper() == tag.ToUpper())
                         select p).ToList();
            }

            if (!string.IsNullOrEmpty(pesquisa))
            {
                posts = (from p in posts
                         where p.Titulo.ToUpper().Contains(pesquisa.ToUpper())
                            || p.Resumo.ToUpper().Contains(pesquisa.ToUpper())
                            || p.Descricao.ToUpper().Contains(pesquisa.ToUpper())
                         select p).ToList();
            }

            var totalRegistros = posts.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdRegistrosPular = (indiceDaPagina * registrosPorPagina);
            var qtdePaginas = (int)Math.Ceiling((decimal)totalRegistros / registrosPorPagina);

            viewModel.Posts = (from p in posts
                               orderby p.DataPublicacao descending
                               select new DetalhesPostViewModel
                               {
                                   DataPublicacao = p.DataPublicacao,
                                   Autor = p.Autor,
                                   Descricao = p.Descricao,
                                   Id = p.Id,
                                   Resumo = p.Resumo,
                                   Titulo = p.Titulo,
                                   Visivel = p.Visivel,
                                   QtdeComentarios = p.Comentario.Count
                               }).Skip(qtdRegistrosPular).Take(registrosPorPagina).ToList();
            viewModel.TotalPaginas = qtdePaginas;
            viewModel.PaginaAtual = paginaCorreta;
            viewModel.Tag = tag;
            viewModel.Tags = (from p in conexao.TagClass
                              where conexao.TagPosts.Any(x => x.IdTag == p.Tag)
                              orderby p.Tag
                              select p.Tag).ToList();
            viewModel.Pesquisa = pesquisa;

            return View(viewModel);
        }

        public ActionResult _Paginacao()
        {
            return PartialView();
        }

        public ActionResult Post(int id, int? pagina)
        {
            var viewModel = new DetalhesPostViewModel();
            var conexao = new ConexaoBanco();

            var post = (from x in conexao.Posts where x.Id == id select x).FirstOrDefault();

            if (post == null)
            {
                throw new Exception(string.Format("Erro"));
            }

            preencherViewModel(viewModel, post, pagina);

            return View(viewModel);
        }

        private static void preencherViewModel(DetalhesPostViewModel viewModel, Post post, int? pagina)
        {
            viewModel.Id = post.Id;
            viewModel.Autor = post.Autor;
            viewModel.DataPublicacao = post.DataPublicacao;
            viewModel.Descricao = post.Descricao;
            viewModel.HoraPublicacao = post.DataPublicacao;
            viewModel.Resumo = post.Resumo;
            viewModel.Titulo = post.Titulo;
            viewModel.QtdeComentarios = post.Comentario.Count;
            viewModel.Tags = (from p in post.TagsPost
                              select p.IdTag).ToList();

            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registrosPorPagina = 3;
            var totalRegistros = post.Comentario.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdRegistrosPular = (indiceDaPagina * registrosPorPagina);
            var qtdePaginas = (int)Math.Ceiling((decimal)totalRegistros / registrosPorPagina);

            viewModel.Comentarios = (from p in post.Comentario
                                     orderby p.DataHora
                                     select p).Skip(qtdRegistrosPular).Take(registrosPorPagina).ToList();

            viewModel.PaginaAtual = paginaCorreta;
            viewModel.TotalPaginas = qtdePaginas;
        }

        [HttpPost]
        public ActionResult Post(DetalhesPostViewModel viewModel)
        {
            var conexao = new ConexaoBanco();
            var post = (from p in conexao.Posts
                        where p.Id == viewModel.Id
                        select p).FirstOrDefault();

            if (ModelState.IsValid)
            {
                if (post == null)
                {
                    throw new Exception(string.Format("Post código {0} não encontrado.", viewModel.Id));
                }

                var comentario = new Comentario();

                comentario.AdmPost = HttpContext.User.Identity.IsAuthenticated;
                comentario.Descricao = viewModel.ComentarioDescricao;
                comentario.Email = viewModel.ComentarioEmail;
                comentario.IdPost = viewModel.Id;
                comentario.Nome = viewModel.ComentarioNome;
                comentario.PaginaWeb = viewModel.ComentarioPaginaWeb;
                comentario.DataHora = DateTime.Now;

                try
                {
                    conexao.Comentarios.Add(comentario);
                    conexao.SaveChanges();
                    return Redirect(Url.Action("Post", new
                    {
                        ano = post.DataPublicacao.Year,
                        mes = post.DataPublicacao.Month,
                        dia = post.DataPublicacao.Day,
                        titulo = post.Titulo,
                        id = post.Id
                    }) + "#comentarios");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("", exp.Message);
                }
            }

            preencherViewModel(viewModel, post, null);

            return View(viewModel);
        }

        public ActionResult _PaginacaoPost()
        {
            return PartialView();
        }
    }
}

BlogFilipe.web/Views/Blog/Index.cshtml
@model BlogFilipe.web.Models.Blog.ListarPostsViewModel
@{
    ViewBag.Title = "Posts";
    var tipoPesquisa = "";
    if (Model.Tag != null)
    {
        tipoPesquisa = string.Format(" - Tag: {0}", Model.Tag);
    }
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Blog/Index.js")"></script>
}

<h1>Posts @tipoPesquisa</h1>
<div class="row">
    <div class="col-md-10">
        @foreach (var item in Model.Posts)
        {
            <h2>
                @Html.ActionLink(item.Titulo, "Post", "Blog", new
           {
               id = item.Id,
               ano = item.DataPublicacao.Year,
               mes = item.DataPublicacao.Month,
               dia = item.DataPublicacao.Day,
               titulo = item.Titulo
           }, null)
            </h2>

            <div class="div-imagem icone-calendario"></div>
            @item.DataPublicacao.ToString("dd/MM/yyyy HH:mm")

            <div class="div-imagem icone-autor"></div>
            @item.Autor

            <div class="div-imagem icone-comentario"></div>
            <a href="@Url.Action("Post", "Blog", new{ id = item.Id,
                                                      ano = item.DataPublicacao.Year,
                                                      mes = item.DataPublicacao.Month,
                                                      dia = item.DataPublicacao.Day,
                                                      titulo = item.Titulo })#comentarios">@item.QtdeComentarios</a>

            if (Request.IsAuthenticated)
            {
                <div class="div-imagem icone-editar"></div>
                @Html.ActionLink("Editar", "EditarPost", "Administracao", new { id = item.Id }, null)

                <div class="div-imagem icone-excluir"></div>
                @Html.ActionLink("Excluir", "ExcluirPost", "Administracao", new { id = item.Id }, new { @class = "excluir-post" })
            }

            <div>@item.Resumo</div>
            @Html.ActionLink("Continue lendo...", "Post", "Blog", new
       {
           id = item.Id,
           ano = item.DataPublicacao.Year,
           mes = item.DataPublicacao.Month,
           dia = item.DataPublicacao.Day,
           titulo = item.Titulo
       }, null)
        }
    </div>

    <div class="col-md-2">
        <h3>Tags</h3>
        <ul>
            @foreach (var item in Model.Tags)
            {
                <li>@Html.ActionLink(item, "Index", "Blog", new { tag = item }, null)</li>
            }
        </ul>
    </div>
</div>

@Html.Partial("_Paginacao", Model)

BlogFilipe.web/Views/Blog/Post.cshtml
@model BlogFilipe.web.Models.Blog.DetalhesPostViewModel
@{
    ViewBag.Title = "Post";
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Blog/Index.js")"></script>
}

<h2>@Model.Titulo</h2>

<div class="div-imagem icone-calendario"></div>
@Model.DataPublicacao.ToString("dd/MM/yyyy HH:mm")

<div class="div-imagem icone-autor"></div>
@Model.Autor

<div class="div-imagem icone-comentario"></div>
<a href="@Url.Action("Post", "Blog", new{ id = Model.Id,
                                          ano = Model.DataPublicacao.Year,
                                          mes = Model.DataPublicacao.Month,
                                          dia = Model.DataPublicacao.Day,
                                          titulo = Model.Titulo })#comentarios">@Model.QtdeComentarios</a>

@if (Request.IsAuthenticated)
{
    <div class="div-imagem icone-excluir"></div>
    @Html.ActionLink("Excluir", "ExcluirPost", "Administracao", new { id = Model.Id }, new { @class = "excluir-post" })
}

<div>
    @Model.Descricao
</div>

<h3>Tags</h3>

<div>
    <ul class="div-lista">
        @if (Model.Tags != null)
        {
            foreach (var item in Model.Tags)
            {
                <li>
                    @Html.ActionLink(item, "Index", "Blog", new { tag = item }, null)                   
                </li>
            }
        }
    </ul>
</div>

<div id="comentarios">
    <h3>Novo comentário</h3>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(x => x.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioNome)
            @Html.TextBoxFor(m => m.ComentarioNome, new { @class = "form-control"})
            @Html.ValidationMessageFor(m => m.ComentarioNome)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioEmail)
            @Html.TextBoxFor(m => m.ComentarioEmail, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioEmail)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioPaginaWeb)
            @Html.TextBoxFor(m => m.ComentarioPaginaWeb, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioPaginaWeb)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioDescricao)
            @Html.TextAreaFor(m => m.ComentarioDescricao, new { rows = 8, @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioDescricao)
        </div>
        <p>
            <input type="submit" value="Salvar" class="btn btn-primary"/>
        </p>
    }
    <div>
        <h3>Comentários</h3>
        @{
            var contador = 0;
        }
        @foreach (var item in Model.Comentarios)
        {
            contador++;
            string id = "comentario" + contador.ToString();
            string cssClass = "text-info";
            if (item.AdmPost)
            {
                cssClass = "label label-info";
            }
            <div>
                <a id="@item.Id"></a>
                <p>
                    <span class="@cssClass">@item.Nome</span><br />
                    <small>
                        @item.DataHora.ToString("dd/MM/yyyy HH:mm:ss")
                        @if (!string.IsNullOrEmpty(item.PaginaWeb))
                        {
                            <text>|</text>
                            <a href="@item.PaginaWeb">@item.PaginaWeb</a>
                        }
                        @if (this.Request.IsAuthenticated)
                        {
                            <text>|</text>
                            @Html.ActionLink("Remover", "ExcluirComentario", "Administracao", new { id = item.Id }, new { @class = "excluir-comentario" })
                        }
                    </small>
                </p>
                @Html.Raw(Html.Encode(item.Descricao).Replace("\n", "<br />"))
            </div>

            if (contador < this.Model.Comentarios.Count)
            {
                <hr />
            }
        }
    </div>
    @Html.Partial("_PaginacaoPost", Model)
</div>

BlogFilipe.web/Views/Blog/_Paginacao.cshtml
@model BlogFilipe.web.Models.Blog.ListarPostsViewModel
@if (Model.TotalPaginas > 1)
{
    var proximaPagina = Model.PaginaAtual + 1;
    var paginaAnterior = Model.PaginaAtual - 1;

    <div class="pagination">
        @if (Model.PaginaAtual > 1)
        {
            @Html.ActionLink("Página anterior", "Index", "Blog", new { pagina = paginaAnterior, tag = Model.Tag, pesquisa = Model.Pesquisa }, new { rel = "prev" })
        }
        @if (Model.PaginaAtual < Model.TotalPaginas)
        {
            @Html.ActionLink("Próxima página", "Index", "Blog", new { pagina = proximaPagina, tag = Model.Tag, pesquisa = Model.Pesquisa }, new { rel = "next" })
        }
    </div>
}

BlogFilipe.web/Views/Blog/_PaginacaoPost.cshtml
@model BlogFilipe.web.Models.Blog.DetalhesPostViewModel
@if (Model.TotalPaginas > 1)
{
    var proximaPagina = Model.PaginaAtual + 1;
    var paginaAnterior = Model.PaginaAtual - 1;

    <div class="pagination">
        @if (Model.PaginaAtual > 1)
        {
            <a href="@Url.Action("Post", new
                {
                    id = Model.Id,
                    pagina = paginaAnterior
                })#comentarios" rel="prev">Página anterior</a>
            if(proximaPagina != -1)
            {
                <text>|</text>
            }
        }

        @if (Model.PaginaAtual < Model.TotalPaginas)
        {
            <a href="@Url.Action("Post", new
                {
                    id = Model.Id,
                    pagina = proximaPagina
                })#comentarios" rel="prev">Próxima página</a>
        }
    </div>
}